from utils.str_to_list_fn import str_to_list_fn
from utils.augmentation import augmentation_fn
from utils.configure_optimizer_loss import configure_optimizer_loss 
from utils.configure_optimizer_loss import configure_optimizer_loss_2nd
from utils.init_gpus import init_gpus
from utils.show_batch import show_batch
from utils.label_encoder import  age_encode
from utils.label_encoder import  age_encode_2
from utils.label_encoder import  age_encode_utk
from utils.label_encoder import  age_encode_regression
from utils.label_encoder import  get_age_encoder
from utils.label_encoder import  get_age_decoder
from utils.model_utils import set_conv_trainable_false
from utils.setup_output_directories import setup_output_directories
from utils.setup_output_directories import setup_output_directories_2nd
from utils.preprocessing import preprocess_input
from utils.visualize_utils import barplot
from utils.add_regularization import add_regularization
from utils.ordinal_metrics    import MeanAbsoluteErrorLabels
from utils.ordinal_layer      import CoralOrdinal
from utils.ordinal_activation import ordinal_softmax
#from utils.ordinal_loss       import OrdinalCrossEntropy
from utils.GradientReversalLayer import GradientReversalLayer
from utils.gradientNull import GradientNull
from utils.MeanAbsoluteDifference import MeanAbsoluteDifference
from utils.metrics import *